name = "is42s32400f"
description = "IS42S32400F SDRAM chip driver - generic over FMC bus primitives"
version = "0.1.0"
licenses = "Apache-2.0"
maintainers = ["Olivier Henley <olivier.henley@adacore.com>"]

[build-switches]
"*".runtime_checks = "none"

[[depends-on]]
machine_types = "*"
sdram_generic = "*"

[[pins]]
machine_types = { url = "https://github.com/GNAT-Academic-Program/machine_types.git", branch = "main" }
sdram_generic = { url = "https://github.com/GNAT-Academic-Program/sdram_generic.git", branch = "main" }
